### GET Request: Get User by ID ###
GET http://localhost:8081/api/users/1

### GET Request: Get User by Email ###
GET http://localhost:8081/api/users/emails?email=altin@office.com

### GET Request: Get All Users ###
GET http://localhost:8081/api/users/all

### POST Request: Create User ###
POST http://localhost:8081/api/users/create
Content-Type: application/json

{
  "salutation": "MALE",
  "firstName": "Test",
  "lastName": "Altin",
  "email": "altin@test.com",
  "password": "secret",
  "country": "USA",
  "role": 0
}

### POST Request: Create User with Email Error ###
POST http://localhost:8081/api/users/create
Content-Type: application/json

{
  "salutation": "MALE",
  "firstName": "Test",
  "lastName": "Altin",
  "password": "secret",
  "country": "USA",
  "role": 0
}

### PUT Request: Update User by ID ###
PUT http://localhost:8081/api/users/5
Content-Type: application/json

{
  "salutation": "MALE",
  "firstName": "Change",
  "lastName": "Altin",
  "email": "altin@office.com",
  "password": "newsecret",
  "country": "Canada",
  "role": 1
}

### DELETE Request: Delete User by ID ###
DELETE http://localhost:8081/api/users/5
