### GET Request: Get Quiz by ID ###
GET http://localhost:8081/api/quizzes/1

### Get Quiz by Category
GET http://localhost:8081/api/quizzes/categories/SPORTS

### Get Quiz by Category - Error
GET http://localhost:8081/api/quizzes/categories/TEST

### Create Quiz Geography
POST http://localhost:8081/api/quizzes/createQuiz
Content-Type: application/json

{
  "creatorId": 1,
  "category": "GEOGRAPHY",
  "startDate": "2023-10-18",
  "duration": 30,
  "questions": [
    {
      "question": "What is the capital of France?",
      "answerOptions": [
        {
          "answer": "Paris",
          "correct": true
        },
        {
          "answer": "London",
          "correct": false
        },
        {
          "answer": "Berlin",
          "correct": false
        },
        {
          "answer": "Madrid",
          "correct": false
        }
      ]
    },
    {
      "question": "What is the largest planet in our solar system?",
      "answerOptions": [
        {
          "answer": "Jupiter",
          "correct": true
        },
        {
          "answer": "Mars",
          "correct": false
        },
        {
          "answer": "Venus",
          "correct": false
        },
        {
          "answer": "Saturn",
          "correct": false
        }
      ]
    },
    {
      "question": "Which country is known as the Land of the Rising Sun?",
      "answerOptions": [
        {
          "answer": "Japan",
          "correct": true
        },
        {
          "answer": "China",
          "correct": false
        },
        {
          "answer": "South Korea",
          "correct": false
        },
        {
          "answer": "Vietnam",
          "correct": false
        }
      ]
    }
  ]
}

### Create Quiz Sports
POST http://localhost:8081/api/quizzes/createQuiz
Content-Type: application/json

{
  "creatorId": 1,
  "category": "SPORTS",
  "startDate": "2023-10-18",
  "duration": 30,
  "questions": [
    {
      "question": "Who won the FIFA World Cup in 2018?",
      "category": "SPORTS",
      "answerOptions": [
        {
          "answer": "France",
          "correct": true
        },
        {
          "answer": "Brazil",
          "correct": false
        },
        {
          "answer": "Germany",
          "correct": false
        },
        {
          "answer": "Spain",
          "correct": false
        }
      ]
    },
    {
      "question": "Who is the all-time leading scorer in NBA history?",
      "category": "SPORTS",
      "answerOptions": [
        {
          "answer": "Kareem Abdul-Jabbar",
          "correct": true
        },
        {
          "answer": "LeBron James",
          "correct": false
        },
        {
          "answer": "Michael Jordan",
          "correct": false
        },
        {
          "answer": "Kobe Bryant",
          "correct": false
        }
      ]
    }
  ]
}


### Get All Quizzes
GET http://localhost:8081/api/quizzes/all

### Get All Questions by Quiz ID
GET http://localhost:8081/api/quizzes/1/questions

### Get All Questions by Quiz ID - QuizNotFoundException
GET http://localhost:8081/api/quizzes/9999/questions

### Delete Quiz by ID
DELETE http://localhost:8081/api/quizzes/3
