### Create User
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "salutation": "MALE",
  "firstName": "Test",
  "lastName": "Altin",
  "emailOrUsername": "altin@test.com",
  "password": "secretsecret",
  "country": "USA",
  "role": "USER",
  "userStatistic": {
    "points": 10
  }
}

### Create second User
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "salutation": "MALE",
  "firstName": "User",
  "lastName": "Eins",
  "emailOrUsername": "username",
  "password": "secretsecret",
  "country": "AUT",
  "role": "ADMIN",
  "userStatistic": {
    "points": 10
  }
}

### Create User - Validation Error (eMail)
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "salutation": "MALE",
  "firstName": "Test",
  "lastName": "Altin",
  "emailOrUsername": "ma",
  "password": "secretsecret",
  "country": "USA",
  "role": "USER",
  "userStatistic": {
    "points": 10
  }
}

### Login User Successfull
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "altin@test.com",
  "password": "secretsecret"
}

### Login User Wrong password
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "altin@test.com",
  "password": "wrongpassword"
}

### Login User Wrong email
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "wrong@mail.com",
  "password": "wrongpassword"
}

### Get User by ID 1
GET http://localhost:8081/api/users/1

### Get User by Email
GET http://localhost:8081/api/users/emails?email=altin@test.com

### Get User by Email - ConstraintViolationException
GET http://localhost:8081/api/users/emails?email=altin

### Get All Users
GET http://localhost:8081/api/users/all

### Get User - UserNotFoundException
GET http://localhost:8081/api/users/9999

### Update User by ID
PUT http://localhost:8081/api/users/1
Content-Type: application/json

{
  "salutation": "MALE",
  "firstName": "Change",
  "lastName": "Altin",
  "emailOrUsername": "altin@changeMail.com",
  "password": "newsecret",
  "country": "CAN",
  "role": "ADMIN"
}

### Delete User by ID
DELETE http://localhost:8081/api/users/2
